title: Meet the Carsons
author: Robert Carson
email: robert.carson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An Awesome Family Blog filled with happy family stuff.
  
github_username:  meetthecarsons

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
