title: Meet the Carsons
author: Robert Carson
email: robert.carson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An Awesome Family Blog filled with happy family stuff.

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
exclude:
  - Gemfile
  - Gemfile.lock
